import os
import zipfile
import hashlib
import json
from datetime import datetime
from typing import Dict, List, Tuple, Optional, Any
import numpy as np

class ReportingSuite:
    """Advanced reporting and research export engine."""

    @staticmethod
    def generate_pdb(seq: str, coords: np.ndarray, confidence: Optional[np.ndarray] = None, **kwargs) -> str:
        """
        Generate PDB 3.3 formatted string. 
        Handles CA-only or All-Atom manifold with high-fidelity resonance metadata.
        """
        lines = [f"HEADER    PROTEIN STRUCTURE GENERATED BY RESONANCE-FOLD v2026"]
        lines.append(f"TITLE     NRC PHI-LATTICE REFINEMENT JOB - DETERMINISTIC MANIFOLD")
        
        # Center coordinates for optimal visualizer resonance
        if coords is not None and len(coords) > 0:
            center = np.mean(coords, axis=0)
            coords = coords - center
            
        atom_types = kwargs.get("atom_types")
        res_indices = kwargs.get("res_indices")
        res_names = kwargs.get("res_names")

        if atom_types and res_indices and res_names:
            # All-Atom Mode (REFOLD-Proof)
            for i, (pos, atype, res_idx, rname) in enumerate(zip(coords, atom_types, res_indices, res_names)):
                res_name_3 = ReportingSuite.get_3letter(rname)
                conf_val = float(confidence[i]) if (confidence is not None and i < len(confidence)) else 100.0
                element = atype[0] if atype[0] in "CNOSP" else "C"
                # PDB Format: ATOM, Serial, Name, AltLoc, ResName, Chain, ResSeq, iCode, X, Y, Z, Occ, B-factor, Element
                lines.append(f"ATOM  {i+1:5} {atype:^4} {res_name_3} A{res_idx:4}    {pos[0]:8.3f}{pos[1]:8.3f}{pos[2]:8.3f}  1.00 {conf_val:6.2f}           {element}")
        else:
            # CA-Only Fallback
            if confidence is None:
                confidence = np.full(len(seq), 100.0)
            for i, (aa, pos) in enumerate(zip(seq, coords)):
                res_name = ReportingSuite.get_3letter(aa)
                conf_val = float(confidence[i])
                lines.append(f"ATOM  {i+1:5}  CA  {res_name} A{i+1:4}    {pos[0]:8.3f}{pos[1]:8.3f}{pos[2]:8.3f}  1.00 {conf_val:6.2f}           C")
                
        lines.append("TER")
        lines.append("END")
        return "\n".join(lines)

    @staticmethod
    def create_research_package(job_id: str, seq: str, coords: np.ndarray, confidence: np.ndarray, analysis: Dict, meta: Dict) -> str:
        """Assemble comprehensive research package with complete data manifold in /tmp."""
        import shutil
        temp_dir = f"/tmp/nrc_job_{job_id}"
        if os.path.exists(temp_dir):
            shutil.rmtree(temp_dir)
        os.makedirs(temp_dir, exist_ok=True)
        
        # Extract all-atom metadata if present
        all_atom_kwargs = {}
        if meta.get("all_atom"):
            all_atom_kwargs = {
                "atom_types": meta.get("atom_types"),
                "res_indices": meta.get("res_indices"),
                "res_names": meta.get("res_names")
            }
        
        # 1. PDB File (with actual B-factors)
        pdb_path = os.path.join(temp_dir, f"{job_id}.pdb")
        with open(pdb_path, "w") as f:
            f.write(ReportingSuite.generate_pdb(seq, coords, confidence, **all_atom_kwargs))
            
        # 2. Resonance Certificate (Mathematical Proof)
        cert_path = os.path.join(temp_dir, "resonance_certificate.json")
        certificate = ReportingSuite.generate_resonance_certificate(seq, coords, meta)
        with open(cert_path, "w") as f:
            json.dump(certificate, f, indent=4)

        # 3. Metadata JSON
        meta_path = os.path.join(temp_dir, "metadata.json")
        with open(meta_path, "w") as f:
            # Convert numpy types to native for JSON serialization
            json_meta = {k: float(v) if isinstance(v, (np.float32, np.float64)) else v for k, v in meta.items()}
            # Remove bulky arrays from JSON meta to keep it clean
            json_meta.pop("atom_types", None)
            json_meta.pop("res_indices", None)
            json_meta.pop("res_names", None)
            json.dump({**json_meta, "certificate_id": certificate["certificate_id"], "timestamp": str(datetime.now())}, f, indent=4)
            
        # 3. Trajectory CSV (Summary only for large manifolds)
        csv_path = os.path.join(temp_dir, "lattice_summary.csv")
        with open(csv_path, "w") as f:
            if not meta.get("all_atom"):
                f.write("Index,Residue,X,Y,Z,Confidence\n")
                for i, (aa, pos) in enumerate(zip(seq, coords)):
                    f.write(f"{i},{aa},{pos[0]:.4f},{pos[1]:.4f},{pos[2]:.4f},{confidence[i]:.2f}\n")
            else:
                f.write("Index,Atom,Residue,ResIdx,X,Y,Z\n")
                for i, (pos, atype, rname, ridx) in enumerate(zip(coords, meta["atom_types"], meta["res_names"], meta["res_indices"])):
                    f.write(f"{i},{atype},{rname},{ridx},{pos[0]:.4f},{pos[1]:.4f},{pos[2]:.4f}\n")

        # 4. Biophysics Report (Styled HTML)
        report_path = os.path.join(temp_dir, "report.html")
        avg_conf = meta.get('avg_confidence', 0)
        with open(report_path, "w") as f:
            f.write(f"""
            <html><head><style>
                body {{ font-family: 'Inter', sans-serif; background: #0d0d0e; color: #e0e0e0; padding: 40px; line-height: 1.6; }}
                .card {{ background: #1a1a1b; border: 1px solid #D4AF37; padding: 30px; border-radius: 12px; box-shadow: 0 10px 30px rgba(0,0,0,0.5); }}
                h1 {{ color: #D4AF37; border-bottom: 2px solid #D4AF37; padding-bottom: 10px; text-transform: uppercase; letter-spacing: 2px; }}
                h3 {{ color: #D4AF37; margin-top: 30px; }}
                li {{ margin: 12px 0; list-style-type: square; }}
                .stat-val {{ font-weight: bold; color: #fff; }}
                .footer {{ margin-top: 40px; font-size: 0.8rem; color: #666; text-align: center; border-top: 1px solid #333; padding-top: 20px; }}
            </style></head><body>
            <div class="card">
                <h1>Resonance-Fold Research Report</h1>
                <p><strong>Job ID:</strong> <span class="stat-val">{job_id}</span></p>
                <p><strong>Sequence:</strong> <br><code style="word-break: break-all; color: #D4AF37;">{seq}</code></p>
                <hr style="border-color: #333;">
                <h3>Structural Analysis</h3>
                <ul>
                    <li><strong>Isoelectric Point (pI):</strong> <span class="stat-val">{analysis['pI']:.2f}</span></li>
                    <li><strong>TTT-7 Stability:</strong> <span class="stat-val">{meta.get('ttt_stability', 0):.4f}</span></li>
                    <li><strong>Average Confidence (pLDDT):</strong> <span class="stat-val">{avg_conf:.2f}%</span></li>
                    <li><strong>Resolution:</strong> <span class="stat-val">{"All-Atom Manifold" if meta.get("all_atom") else "C-alpha Skeleton"}</span></li>
                    <li><strong>DSSP Sequence:</strong> <br><code style="word-break: break-all;">{"".join(analysis['dssp'])}</code></li>
                </ul>
                <div class="footer">
                    <em>Generated via NRC φ-Lattice Projection Engine v2026. <br>Verified TTT-7 Deterministic Manifold.</em>
                </div>
            </div>
            </body></html>
            """)
            
        # 5. Citations
        cite_path = os.path.join(temp_dir, "citations.bib")
        with open(cite_path, "w") as f:
            f.write("@article{nrc2026,\n  title={Resonance-Fold: Ultra-Scale Protein Folding via Phi-Lattice Refinement},\n  author={Nexus Resonance Codex},\n  year={2026}\n}")
            
        # Zip assembly
        zip_name = f"/tmp/{job_id}.zip"
        with zipfile.ZipFile(zip_name, 'w') as zipf:
            for root, dirs, files in os.walk(temp_dir):
                for file in files:
                    zipf.write(os.path.join(root, file), file)
                    
        return zip_name

    @staticmethod
    def generate_share_hash(seq: str) -> str:
        """Generate deterministic provenance hash."""
        return hashlib.sha256(seq.encode()).hexdigest()[:12]

    @staticmethod
    def generate_resonance_certificate(seq: str, coords: np.ndarray, meta: Dict) -> Dict:
        """Calculates mathematical resonance proof (TTT-7 stability)."""
        stability = meta.get("ttt_stability", 7.0)
        # Calculate deterministic digital root of the structure
        structural_sum = np.sum(np.abs(coords))
        dr = (structural_sum - 1) % 9 + 1
        
        return {
            "certificate_id": f"NRC-{hashlib.md5(seq.encode()).hexdigest()[:8].upper()}",
            "resonance_factor": float(stability),
            "digital_root_parity": float(dr),
            "ttt7_status": "STABLE" if dr in [1, 2, 4, 5, 7, 8] else "CHAOTIC",
            "mathematical_engine": "NRC Phi-Lattice v2.0",
            "determinism_guarantee": "100% Deterministic (AI-Free)"
        }

    @staticmethod
    def get_3letter(aa: str) -> str:
        """Convert 1-letter amino acid code to 3-letter."""
        d = {'A':'ALA','R':'ARG','N':'ASN','D':'ASP','C':'CYS','Q':'GLN','E':'GLU','G':'GLY','H':'HIS','I':'ILE','L':'LEU','K':'LYS','M':'MET','F':'PHE','P':'PRO','S':'SER','T':'THR','W':'TRP','Y':'TYR','V':'VAL'}
        return d.get(aa, 'UNK')
